language: sh

before_script:
  - sudo add-apt-repository "deb http://mirrors.kernel.org/ubuntu utopic main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq shellcheck

script:
  - shellcheck mac
